version: '3.8'

services:
  # VxDB Insert Service
  vxinsert:
    build:
      context: .
      dockerfile: cmd/vxinsert/Dockerfile
    container_name: vxinsert
    restart: unless-stopped
    command: ["./vxinsert", "--config=/etc/vxdb/config.yaml", "--storage-addrs=vxstorage1:9096,vxstorage2:9096"]
    ports:
      - "8080:8080"    # HTTP API
      - "9091:9091"    # Metrics
      - "9092:9092"    # Dashboard
      - "8081:8081"    # WebSocket
      - "9093:9093"    # gRPC
      - "7946:7946"    # Gossip
      - "7947:7947"    # Serf
    volumes:
      - vxinsert_data:/var/lib/vxdb/data
      - vxinsert_wal:/var/lib/vxdb/wal
      - vxinsert_snapshots:/var/lib/vxdb/snapshots
      - vxinsert_buffer:/var/lib/vxdb/buffer
      - vxinsert_logs:/var/log/vxdb
      - ./configs/vxinsert-production.yaml:/etc/vxdb/config.yaml
    environment:
      - VXDB_CONFIG_FILE=/etc/vxdb/config.yaml
      - GIN_MODE=release
    networks:
      - vxdb_network
    depends_on:
      - vxstorage1
      - vxstorage2
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # VxDB Storage Service
  vxstorage1:
    build:
      context: .
      dockerfile: cmd/vxstorage/Dockerfile
    container_name: vxstorage1
    restart: unless-stopped
    ports:
      - "8082:8082"    # HTTP API
      - "9094:9094"    # Metrics
      - "9095:9095"    # Dashboard
      - "9096:9096"    # gRPC
      - "7948:7948"    # Gossip
      - "7949:7949"    # Serf
    volumes:
      - vxstorage1_data:/var/lib/vxdb/data
      - vxstorage1_wal:/var/lib/vxdb/wal
      - vxstorage1_snapshots:/var/lib/vxdb/snapshots
      - vxstorage1_storage:/var/lib/vxdb/storage
      - vxstorage1_temp:/var/lib/vxdb/temp
      - vxstorage1_manifest:/var/lib/vxdb/manifest
      - vxstorage1_backups:/var/lib/vxdb/backups
      - vxstorage1_logs:/var/log/vxdb
      - ./configs/vxstorage-production.yaml:/etc/vxdb/config.yaml
    environment:
      - VXDB_CONFIG_FILE=/etc/vxdb/config.yaml
      - GIN_MODE=release
    networks:
      - vxdb_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  vxstorage2:
    build:
      context: .
      dockerfile: cmd/vxstorage/Dockerfile
    container_name: vxstorage2
    restart: unless-stopped
    ports:
      - "8084:8082"    # HTTP API
      - "9104:9094"    # Metrics
      - "9105:9095"    # Dashboard
      - "9097:9096"    # gRPC
      - "7952:7948"    # Gossip
      - "7953:7949"    # Serf
    volumes:
      - vxstorage2_data:/var/lib/vxdb/data
      - vxstorage2_wal:/var/lib/vxdb/wal
      - vxstorage2_snapshots:/var/lib/vxdb/snapshots
      - vxstorage2_storage:/var/lib/vxdb/storage
      - vxstorage2_temp:/var/lib/vxdb/temp
      - vxstorage2_manifest:/var/lib/vxdb/manifest
      - vxstorage2_backups:/var/lib/vxdb/backups
      - vxstorage2_logs:/var/log/vxdb
      - ./configs/vxstorage-production.yaml:/etc/vxdb/config.yaml
    environment:
      - VXDB_CONFIG_FILE=/etc/vxdb/config.yaml
      - GIN_MODE=release
    networks:
      - vxdb_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # VxDB Search Service
  vxsearch:
    build:
      context: .
      dockerfile: cmd/vxsearch/Dockerfile
    container_name: vxsearch
    restart: unless-stopped
    command: ["./vxsearch", "--config=/etc/vxdb/config.yaml", "--storage-addrs=vxstorage1:9096,vxstorage2:9096"]
    ports:
      - "8083:8083"    # HTTP API
      - "9106:9097"    # Metrics
      - "9098:9098"    # Dashboard
      - "9099:9099"    # gRPC
      - "7950:7950"    # Gossip
      - "7951:7951"    # Serf
    volumes:
      - vxsearch_data:/var/lib/vxdb/data
      - vxsearch_wal:/var/lib/vxdb/wal
      - vxsearch_snapshots:/var/lib/vxdb/snapshots
      - vxsearch_cache:/var/lib/vxdb/cache
      - vxsearch_logs:/var/log/vxdb
      - ./configs/vxsearch-production.yaml:/etc/vxdb/config.yaml
    environment:
      - VXDB_CONFIG_FILE=/etc/vxdb/config.yaml
      - GIN_MODE=release
    networks:
      - vxdb_network
    depends_on:
      - vxstorage1
      - vxstorage2
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  # VxDB Insert Service volumes
  vxinsert_data:
    driver: local
  vxinsert_wal:
    driver: local
  vxinsert_snapshots:
    driver: local
  vxinsert_buffer:
    driver: local
  vxinsert_logs:
    driver: local

  # VxDB Storage Service volumes
  vxstorage1_data:
    driver: local
  vxstorage1_wal:
    driver: local
  vxstorage1_snapshots:
    driver: local
  vxstorage1_storage:
    driver: local
  vxstorage1_temp:
    driver: local
  vxstorage1_manifest:
    driver: local
  vxstorage1_backups:
    driver: local
  vxstorage1_logs:
    driver: local

  vxstorage2_data:
    driver: local
  vxstorage2_wal:
    driver: local
  vxstorage2_snapshots:
    driver: local
  vxstorage2_storage:
    driver: local
  vxstorage2_temp:
    driver: local
  vxstorage2_manifest:
    driver: local
  vxstorage2_backups:
    driver: local
  vxstorage2_logs:
    driver: local

  # VxDB Search Service volumes
  vxsearch_data:
    driver: local
  vxsearch_wal:
    driver: local
  vxsearch_snapshots:
    driver: local
  vxsearch_cache:
    driver: local
  vxsearch_logs:
    driver: local

networks:
  vxdb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
