# VexDB Storage Service Production Configuration
# This configuration is optimized for production environments

# Server configuration
server:
  host: "0.0.0.0"
  port: 8082
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_header_bytes: 1048576  # 1MB
  shutdown_timeout: 30s

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, stderr, or file path
  file:
    path: "/var/log/vexdb/vexstorage.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true
  encoding: "json"
  encoder_config:
    message_key: "message"
    level_key: "level"
    time_key: "timestamp"
    name_key: "logger"
    caller_key: "caller"
    stacktrace_key: "stacktrace"
    line_ending: "\n"
    time_format: "RFC3339"

# Metrics configuration
metrics:
  enabled: true
  host: "0.0.0.0"
  port: 9094
  path: "/metrics"
  namespace: "vexdb"
  subsystem: "storage"
  buckets: [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]
  enable_profiling: false
  profiling_port: 6063

# Tracing configuration
tracing:
  enabled: true
  service_name: "vexstorage"
  endpoint: "http://jaeger:14268/api/traces"
  sampling_rate: 0.1  # 10% sampling in production
  batch_size: 512
  timeout: 30s
  max_payload: 4096

# Monitoring configuration
monitoring:
  enabled: true
  collect_interval: 15s
  health_check_interval: 30s
  enable_profiling: false
  profiling_port: 6064

# Dashboard configuration
dashboard:
  enabled: true
  host: "0.0.0.0"
  port: 9095
  base_path: "/"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  enable_profiling: false
  profiling_path: "/debug/pprof"
  enable_pprof: false
  pprof_path: "/debug/pprof"
  enable_metrics: true
  metrics_path: "/metrics"
  enable_health: true
  health_path: "/health"
  enable_debug: false
  debug_path: "/debug"

# Cluster configuration
cluster:
  name: "vexdb-cluster"
  node_id: ""  # Auto-generated if empty
  data_dir: "/var/lib/vexdb/data"
  wal_dir: "/var/lib/vexdb/wal"
  snapshot_dir: "/var/lib/vexdb/snapshots"
  join: []  # List of existing nodes to join
  bootstrap_expect: 3  # Expected number of nodes in cluster
  retry_join:
    enabled: true
    interval: 30s
    max_attempts: 10
  gossip:
    enabled: true
    port: 7948
    bind_addr: "0.0.0.0"
    advertise_addr: ""  # Auto-detected if empty
  serf:
    enabled: true
    port: 7949
    bind_addr: "0.0.0.0"
    advertise_addr: ""  # Auto-detected if empty

# Storage configuration
storage:
  # Data directory configuration
  data_dir: "/var/lib/vexdb/storage"
  wal_dir: "/var/lib/vexdb/wal"
  temp_dir: "/var/lib/vexdb/temp"
  
  # Segment configuration
  segment:
    max_vectors: 10000  # Maximum vectors per segment
    max_size: 104857600  # 100MB maximum segment size
    compression:
      enabled: true
      algorithm: "lz4"
      level: 6
    format_version: 1
    checksum:
      enabled: true
      algorithm: "crc32"
    sync_on_write: false  # Set to true for durability at cost of performance
    preallocate: true  # Preallocate space for segments
  
  # Memory buffer configuration
  memory_buffer:
    enabled: true
    max_size: 1073741824  # 1GB
    flush_interval: 5s
    flush_threshold: 0.8  # Flush when 80% full
    sync_on_flush: false
    compression:
      enabled: true
      algorithm: "lz4"
      level: 6
  
  # Cache configuration
  cache:
    enabled: true
    type: "lru"  # lru, lfu, arc
    size: 536870912  # 512MB
    ttl: 3600s  # 1 hour
    eviction_policy: "lru"
    stats:
      enabled: true
      interval: 60s
  
  # Index configuration
  index:
    enabled: true
    type: "ivf"  # ivf, hnsw, flat
    ivf:
      nlist: 1000  # Number of clusters
      nprobe: 10   # Number of clusters to probe
      quantizer: "pq"  # pq, rq, none
      pq:
        nbits: 8  # Bits per sub-quantizer
        nsubquantizers: 8  # Number of sub-quantizers
    hnsw:
      m: 32  # Number of connections per layer
      ef_construction: 200  # Build time candidates
      ef_search: 100  # Search time candidates
  
  # Manifest configuration
  manifest:
    enabled: true
    path: "/var/lib/vexdb/manifest"
    sync_interval: 5s
    backup_interval: 3600s  # 1 hour
    max_backups: 24  # Keep 24 hours of backups
    compression:
      enabled: true
      algorithm: "lz4"
      level: 6
  
  # WAL configuration
  wal:
    enabled: true
    path: "/var/lib/vexdb/wal"
    max_file_size: 104857600  # 100MB
    max_files: 10
    sync_interval: 1s
    sync_on_write: false  # Set to true for durability
    compression:
      enabled: true
      algorithm: "lz4"
      level: 6
    retention:
      enabled: true
      max_age: 86400s  # 24 hours
      max_size: 1073741824  # 1GB

# Engine configuration
engine:
  # Search configuration
  search:
    max_results: 100
    default_k: 10
    timeout: 30s
    parallel_search: true
    max_concurrent_searches: 1000
    distance_metric: "cosine"  # cosine, euclidean, manhattan
    normalize_vectors: true
    prefilter:
      enabled: true
      max_filters: 100
  
  # Vector configuration
  vector:
    dimension: 0  # 0 means auto-detect from first vector
    type: "float32"  # float32, float64, int8, uint8
    normalize: true
    validation:
      enabled: true
      check_dimension: true
      check_values: true
      min_value: -1.0
      max_value: 1.0
  
  # Metadata configuration
  metadata:
    enabled: true
    max_size: 1048576  # 1MB per vector
    max_keys: 100
    allowed_types: ["string", "number", "boolean", "array"]
    indexing:
      enabled: true
      fields: []  # List of fields to index
      type: "hash"  # hash, btree, gin
  
  # Performance configuration
  performance:
    go_max_procs: 0  # 0 means use all available CPUs
    gc_percent: 100
    memory_limit: "8gb"
    cpu_profile: false
    memory_profile: false
    block_profile: false
    mutex_profile: false
    trace_profile: false
    profile_duration: 30s
    profile_path: "/var/log/vexdb/profile"

# Replication configuration
replication:
  enabled: true
  mode: "async"  # sync, async
  factor: 2  # Number of replicas
  timeout: 30s
  retry:
    enabled: true
    max_attempts: 5
    backoff: "exponential"
    initial_delay: 100ms
    max_delay: 5s
    multiplier: 2.0
    jitter: 0.1
  batch:
    enabled: true
    size: 1000  # Number of operations per batch
    timeout: 1s  # Maximum time to wait for batch
    max_memory: 10485760  # 10MB
  consistency:
    level: "eventual"  # strong, eventual
    read_quorum: 1  # Minimum number of successful reads
    write_quorum: 2  # Minimum number of successful writes

# gRPC server configuration
grpc:
  enabled: true
  port: 9096
  host: "0.0.0.0"
  max_message_size: 4194304  # 4MB
  max_concurrent_streams: 1000
  connection_timeout: 30s
  tls:
    enabled: true
    cert_file: "/etc/vexdb/certs/vexstorage.crt"
    key_file: "/etc/vexdb/certs/vexstorage.key"
    ca_file: "/etc/vexdb/certs/ca.crt"
    client_auth: false
    min_version: "1.2"
    max_version: "1.3"
  keepalive:
    enabled: true
    time: 30s
    timeout: 5s
    permit_without_stream: false
  reflection: false
  interceptors:
    logging: true
    metrics: true
    tracing: true
    recovery: true
    validation: true

# Authentication configuration
auth:
  enabled: true
  type: "api_key"  # none, basic, bearer, api_key
  api_keys: []  # List of valid API keys
  basic_auth:
    users: []  # List of username/password pairs
  bearer_auth:
    tokens: []  # List of valid bearer tokens
  jwt:
    enabled: false
    secret: ""  # JWT secret key
    algorithm: "HS256"
    expiration: 24h
    issuer: "vexdb"
    audience: "vexdb-clients"
  rate_limit:
    enabled: true
    requests_per_second: 10000
    burst: 1000
    by_ip: true
    by_user: false
    by_api_key: true

# Health check configuration
health:
  enabled: true
  path: "/health"
  detailed_path: "/health/detailed"
  check_interval: 30s
  timeout: 10s
  checks:
    - name: "storage"
      type: "storage"
      enabled: true
      timeout: 5s
    - name: "memory"
      type: "memory"
      enabled: true
      timeout: 2s
      threshold: 0.9  # 90% memory usage threshold
    - name: "disk"
      type: "disk"
      enabled: true
      timeout: 5s
      path: "/var/lib/vexdb"
      threshold: 0.9  # 90% disk usage threshold
    - name: "cluster"
      type: "cluster"
      enabled: true
      timeout: 5s

# Circuit breaker configuration
circuit_breaker:
  enabled: true
  timeout: 30s
  max_concurrent_requests: 1000
  error_threshold_percentage: 50
  bulkhead:
    enabled: true
    max_concurrent_calls: 100
    max_wait_duration: 1s
  retry:
    enabled: true
    max_attempts: 3
    wait_duration: 100ms
    backoff_policy: "exponential"
    retryable_status_codes: [408, 429, 500, 502, 503, 504]
    retryable_exceptions: []

# Security configuration
security:
  enabled: true
  tls:
    enabled: true
    cert_file: "/etc/vexdb/certs/vexstorage.crt"
    key_file: "/etc/vexdb/certs/vexstorage.key"
    ca_file: "/etc/vexdb/certs/ca.crt"
    client_auth: false
    min_version: "1.2"
    max_version: "1.3"
    cipher_suites: []
    prefer_server_cipher_suites: true
  encryption:
    enabled: false
    algorithm: "aes-256-gcm"
    key_file: "/etc/vexdb/encryption.key"
  audit:
    enabled: true
    log_file: "/var/log/vexdb/audit.log"
    max_size: 100  # MB
    max_backups: 10
    max_age: 30  # days
    compress: true
    events:
      - "authentication"
      - "authorization"
      - "data_access"
      - "data_modification"
      - "system_events"

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 30  # Keep 30 days of backups
  compression:
    enabled: true
    algorithm: "lz4"
    level: 6
  encryption:
    enabled: false
    algorithm: "aes-256-gcm"
    key_file: "/etc/vexdb/backup.key"
  destination:
    type: "local"  # local, s3, gcs, azure
    path: "/var/lib/vexdb/backups"
    s3:
      bucket: ""
      region: ""
      endpoint: ""
      access_key: ""
      secret_key: ""
    gcs:
      bucket: ""
      credentials_file: ""
    azure:
      container: ""
      account_name: ""
      account_key: ""

# Maintenance configuration
maintenance:
  enabled: true
  compaction:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM
    threshold: 0.3  # Compact when 30% of segments are small
    min_segment_size: 1048576  # 1MB
    max_concurrent_compactions: 2
  optimization:
    enabled: true
    schedule: "0 4 * * 0"  # Weekly on Sunday at 4 AM
    rebuild_indexes: true
    analyze_statistics: true
  cleanup:
    enabled: true
    schedule: "0 1 * * *"  # Daily at 1 AM
    temp_files: true
    old_backups: true
    old_logs: true
    wal_files: true